name: Despliegue Mineria a cPanel
on:
  push:
    branches:
      - produccion
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name "FernandoAcosta97"
          git config --global user.email "teamtareadigital@gmail.com"
      - name: Desplegar a cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.2.2  # O utiliza una versión disponible
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: prueba.com
